[general]
agent_answers_file = "data/agent_answers.txt"
offensive_dict_file = "data/es.txt"
mode = "use_api"  #Opciones: use_api, use_diccionary, use_api_diccionary
languages = ["es"]

[api]
api_key = "USER_API_KEY"
attributes = ["TOXICITY", "INSULT", "IDENTITY_ATTACK", "PROFANITY"]

[risk]
risk_threshold = 0.8 # Umbral de probabilidad para marcar una respuesta como de riesgo según los scores de IA
max_risk_rate = 0.2 # Umbral global de porcentaje de respuestas de riesgo para  bloquear